### ISSUE TITLE
Typo in ImageDocumentSanitizerImple

### ISSUE THREAD

**Issue by xeno6696** [righettod/document-upload-protection#4]
At the OWASP page:

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Protect_FileUpload_Against_Malicious_File.md#case-n3-images `PcxImageParser` is listed twice on lines 127 and 131.  

Please note that the version in the git repo here is also different from what's at the OWASP site.  I would fix it myself but I don't know which version is the right one to use!?

**Comment by righettod** [comment]
Hello, thanks you very much to have spot this error, I will fix it asap!
Thanks again. Regards.

**Comment by righettod** [comment]
Fixed in both repository 😃
